/*
USE test

DECLARE @BEGINTIME DATETIME
DECLARE @ENDTIME DATETIME
DECLARE @ELAPSEDTIME INT--SECONDS

SET @BEGINTIME = GETDATE()
WAITFOR DELAY '00:00:05'
SET @ENDTIME = GETDATE()

SET @ELAPSEDTIME = DATEDIFF(SS,@BEGINTIME,@ENDTIME)

PRINT 'Time Elapsed:'+ CONVERT(VARCHAR,@ELAPSEDTIME) +' Seconds'
*/